<?php

return [
    'storage_type' => 'public',
    'months' => [
        '01' => 'Jan',
        '02' => 'Feb',
        '03' => 'Mar',
        '04' => 'Apr',
        '05' => 'May',
        '06' => 'Jun',
        '07' => 'Jul',
        '08' => 'Aug',
        '09' => 'Sep',
        '10' => 'Oct',
        '11' => 'Nov',
        '12' => 'Dec',
    ],
    'week_days_short' => [
        'Mon' => 'Mon',
        'Tue' => 'Tue',
        'Wed' => 'Wed',
        'Thu' => 'Thu',
        'Fri' => 'Fri',
        'Sat' => 'Sat',
        'Sun' => 'Sun',
    ],
    'week_days' => [
        '1' => 'Mon',
        '2' => 'Tue',
        '3' => 'Wed',
        '4' => 'Thu',
        '5' => 'Fri',
        '6' => 'Sat',
        '0' => 'Sun',
        '7' => 'PH'
    ],
    'email_variables' => [
        1 => [
            'logo',
            'name',
            'email',
            'password',
            'company',
        ],
        2 => [
            'logo',
            'name',
            'url',
            'company',
        ],
    ],
    
    'template_variables' => [
        1 => [
            'Subject' => 'Subject',
            'Serviceagreementbetween' => 'Service Agreement Between',
            'Company' => 'Company',
            'Management' => 'Management',
            'Commencementdate' => 'Commencement Date',
            'Durationofcontract' => 'Duration of contract',
            'Durationofcontractstartdate' => 'Duration of contract start date',
            'Durationofcontractenddate' => 'Duration of contract end date',
            'Contractsum' => 'Contract sum',
            'Contractsuminword' => 'Contract sum in word',
            'Paymenttermseverymonth' => 'Payment terms of every month',
            'Paymenttermsfollowingmonth' => 'Payment terms of following month',
            'Paymenttermsdays' => 'Payment terms of days',
            'Paymenttermsinterestfee' => 'Payment terms of interest fee',
            'Paymenttermsinterestfeedays' => 'Payment terms of interest fee days',
            'Terminationofcontractnotice' => 'Termination of contract notice',
            'Terminationofcontractpayment' => 'Termination of contract payment',
            'Renewalofcontractmonth' => 'Renewal of contract month',
            'Manpowerdeploymentdetail' => 'Manpower deployment detail',
            'Scopeofwork' => 'Scope of work',
            'Extentofworks' => 'Extent of works',
            'Supplies' => 'Supplies',
            'Machinery' => 'Machinery',
            'Externalvendors' => 'External vendors',
        ],
    ],
    'normal_status' => [
        '0' => 'Inactive',
        '1' => 'Active',
    ],
    'currency'=>"₹",
    'update_employee' => "Profile update successfully.",
    'password_update' => "Password updated successfully.",
    'failed_message' => 'Something went wrong',
    'went_wrong_msg' => 'Something went wrong',
];
